---
sudo: required
services:
    - docker

#
# testing multiple subdirectories
# @see https://lord.io/blog/2014/travis-multiple-subdirs/
# @see https://www.dominicrodger.com/tox-and-travis.html
#
language: python
env:
  global:
    - DOCKER_COMPOSE_VERSION=1.8.0
    - COMMIT=${TRAVIS_COMMIT::8}
  matrix:
    - TOX_ENV=crossdock
    - TOX_ENV=py27-tornado42
    - TOX_ENV=py27-tornado43
    - TOX_ENV=pypy-tornado42
    - TOX_ENV=pypy-tornado43
    - TOX_ENV=cover
    - TOX_ENV=flake8
    - TOX_ENV=docs
    - TOX_ENV=benchmark

before_install:
  - make crossdock_install_ci

install:
  - make install

script:
  - make test_ci
  - make crossdock_logs_ci

after_success:
  - coveralls -v
